#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
# shellcheck source=scripts/lib/common.sh
. "$SCRIPT_DIR/lib/common.sh"

CONFIG=
while [ "$#" -gt 0 ]; do
    case "$1" in
        --config) [ "$#" -ge 2 ] || die "--config requires a file"; CONFIG=$2; shift 2 ;;
        -h|--help) printf 'Usage: %s --config FILE\n' "$0"; exit 0 ;;
        *) die "Unknown argument: $1" ;;
    esac
done
[ -n "$CONFIG" ] || die "--config is required"
[ -f "$CONFIG" ] || die "MQTT config not found: $CONFIG"
require_root

allowed='MQTT_HOST MQTT_PORT MQTT_USERNAME MQTT_PASSWORD MQTT_TLS MQTT_DISCOVERY_PREFIX DEVICE_ID DEVICE_NAME TOPIC_ROOT'
seen_host=false
seen_password=false
tls_value=false
while IFS= read -r raw_line || [ -n "$raw_line" ]; do
    line=$(trim_value "$raw_line")
    case "$line" in ''|'#'*) continue ;; esac
    case "$line" in *=*) ;; *) die "Invalid MQTT config line" ;; esac
    key=$(trim_value "${line%%=*}")
    value=$(unquote_value "$(trim_value "${line#*=}")")
    case " $allowed " in *" $key "*) ;; *) die "Unknown MQTT config key: $key" ;; esac
    [ "$key" = MQTT_HOST ] && [ -n "$value" ] && seen_host=true
    [ "$key" = MQTT_PASSWORD ] && [ -n "$value" ] && seen_password=true
    [ "$key" = MQTT_TLS ] && tls_value=$value
done < "$CONFIG"
$seen_host || die "MQTT_HOST is required"
$seen_password || warn "MQTT_PASSWORD is blank; use only if the broker intentionally allows it"
case "$tls_value" in true|false) ;; *) die "MQTT_TLS must be true or false" ;; esac

install -d -o root -g root -m 0755 /etc/reserva-edge
install -o root -g root -m 0600 "$CONFIG" /etc/reserva-edge/mqtt.env

[ -r /etc/reserva-edge/profile.env ] || die "Install the core profile first"
# Root-owned profile generated by install-profile.sh.
# shellcheck disable=SC1091
. /etc/reserva-edge/profile.env

enabled=0
if [ "${ENABLE_NFC:-false}" = true ] && [ -e /sys/class/nfc/nfc0 ]; then
    systemctl enable --now reserva-edge-neard.service reserva-edge-nfc-poll.service reserva-edge-nfc-mqtt.service
    enabled=$((enabled + 1))
fi
if [ "${ENABLE_LED:-false}" = true ]; then
    command -v gpiodetect >/dev/null 2>&1 || die "gpiodetect is required for the LED bridge"
    gpiodetect | grep -q '\[INT33FC:01\]' || die "Verified LED GPIO controller INT33FC:01 is absent"
    systemctl enable --now reserva-edge-led-mqtt.service
    enabled=$((enabled + 1))
fi

[ "$enabled" -gt 0 ] || warn "MQTT config installed, but no optional hardware bridge was enabled"
info "MQTT configuration installed with mode 0600; remove the source config when no longer needed"
